#!/bin/bash
#SBATCH --partition=short
#SBATCH --job-name=test-128-256-dmonly_0007
#SBATCH --time=0:30:00
#SBATCH --nodes=256
#SBATCH --ntasks-per-node=2
#SBATCH --cpus-per-task=16
#SBATCH --mem=115G
#SBATCH --mail-type=end
#SBATCH --mail-user=mho026@ucr.edu
export OMP_NUM_THREADS=32
module unload openmpi
module load mpich
module list
mpirun /rhome/yyang440/bigdata/MP-Gadget3/genic/MP-GenIC _genic_params.ini
python cambpower.py ICS/256_128_99 --czstr 99 --mnu 0
